# Generated by Django 2.2.1 on 2019-06-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
    ]
